// Copyright (c) 2026-present The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <hash.h>
#include <primitives/transaction.h>
#include <script/interpreter.h>
#include <script/script.h>
#include <script/script_error.h>
#include <streams.h>
#include <test/data/pqsig_spending.json.h>
#include <test/util/setup_common.h>
#include <uint256.h>
#include <util/strencodings.h>
#include <util/string.h>

#include <boost/test/unit_test.hpp>

#include <univalue.h>

#include <algorithm>
#include <map>
#include <string>
#include <vector>

// Spend vectors for the draft OP_CHECKPQSIG opcode, generated by
// test/functional/tool_pqsig_spend_vectors.py and carrying full
// transactions. Every witness runs through VerifyScript, so this exercises
// the consensus code rather than a reimplementation of it. The vectors are
// verification vectors: both schemes randomize signing, so the signature is
// given data and what gets re-derived here is everything around it.

BOOST_FIXTURE_TEST_SUITE(pqsig_vector_tests, BasicTestingSetup)

namespace {

struct VectorLeaf {
    int id;
    uint8_t version;
    uint256 hash;
    //! The leaf script itself, kept so the public key commitment can be
    //! checked against the bytes the leaf actually pushes.
    std::vector<unsigned char> script;
    //! Merkle path to this leaf, closest sibling first.
    std::vector<unsigned char> path;
};

//! Hash a scriptTree node (leaf object or two-element array) with the
//! consensus hashing functions, collecting each leaf's path on the way out.
uint256 WalkTree(const UniValue& node, std::vector<VectorLeaf>& leaves)
{
    if (node.isArray()) {
        BOOST_REQUIRE_EQUAL(node.size(), 2U);
        std::vector<VectorLeaf> left, right;
        const uint256 l{WalkTree(node[0], left)};
        const uint256 r{WalkTree(node[1], right)};
        for (auto& leaf : left) leaf.path.insert(leaf.path.end(), r.begin(), r.end());
        for (auto& leaf : right) leaf.path.insert(leaf.path.end(), l.begin(), l.end());
        leaves.insert(leaves.end(), left.begin(), left.end());
        leaves.insert(leaves.end(), right.begin(), right.end());
        return ComputeTapbranchHash(l, r);
    }
    const std::vector<unsigned char> script_bytes{ParseHex(node["script"].get_str())};
    const CScript script(script_bytes.begin(), script_bytes.end());
    const auto version{static_cast<uint8_t>(node["leafVersion"].getInt<int>())};
    const uint256 hash{ComputeTapleafHash(version, script)};
    leaves.push_back({node["id"].getInt<int>(), version, hash, script_bytes, {}});
    return hash;
}

CMutableTransaction DecodeTx(const std::string& hex)
{
    CMutableTransaction mtx;
    const std::vector<unsigned char> raw{ParseHex(hex)};
    SpanReader{raw} >> TX_WITH_WITNESS(mtx);
    return mtx;
}

} // namespace

BOOST_AUTO_TEST_CASE(pqsig_spending)
{
    const script_verify_flags flags{SCRIPT_VERIFY_P2SH | SCRIPT_VERIFY_WITNESS |
                                    SCRIPT_VERIFY_TAPROOT | SCRIPT_VERIFY_P2MR |
                                    SCRIPT_VERIFY_PQSIG};

    UniValue root;
    BOOST_REQUIRE(root.read(json_tests::pqsig_spending));
    BOOST_REQUIRE_EQUAL(root["version"].getInt<int>(), 1);

    // ---- valid spends ----------------------------------------------------
    const UniValue& groups{root["scriptPathSpending"]};
    BOOST_REQUIRE(groups.isArray());
    for (size_t gi{0}; gi < groups.size(); ++gi) {
        const UniValue& group{groups[gi]};
        const CMutableTransaction mtx{DecodeTx(group["auxiliary"]["fullySignedTx"].get_str())};

        std::vector<CTxOut> spent;
        const UniValue& utxos{group["given"]["utxosSpent"]};
        for (size_t i{0}; i < utxos.size(); ++i) {
            const std::vector<unsigned char> spk{ParseHex(utxos[i]["scriptPubKey"].get_str())};
            spent.emplace_back(utxos[i]["amountSats"].getInt<int64_t>(),
                               CScript(spk.begin(), spk.end()));
        }
        BOOST_REQUIRE_EQUAL(spent.size(), mtx.vin.size());

        // The unsigned transaction is the signed one without its witnesses.
        CMutableTransaction stripped{mtx};
        for (auto& in : stripped.vin) in.scriptWitness.stack.clear();
        DataStream unsigned_ser;
        unsigned_ser << TX_NO_WITNESS(stripped);
        BOOST_CHECK_EQUAL(HexStr(unsigned_ser), group["given"]["rawUnsignedTx"].get_str());

        const CTransaction tx{mtx};
        PrecomputedTransactionData txdata;
        txdata.Init(tx, std::vector<CTxOut>{spent});
        BOOST_REQUIRE(txdata.m_bip341_taproot_ready);

        const UniValue& inter{group["intermediary"]};
        BOOST_CHECK_EQUAL(HexStr(txdata.m_prevouts_single_hash), inter["hashPrevouts"].get_str());
        BOOST_CHECK_EQUAL(HexStr(txdata.m_sequences_single_hash), inter["hashSequences"].get_str());
        BOOST_CHECK_EQUAL(HexStr(txdata.m_outputs_single_hash), inter["hashOutputs"].get_str());
        BOOST_CHECK_EQUAL(HexStr(txdata.m_spent_amounts_single_hash), inter["hashAmounts"].get_str());
        BOOST_CHECK_EQUAL(HexStr(txdata.m_spent_scripts_single_hash), inter["hashScriptPubkeys"].get_str());

        const UniValue& inputs{group["inputSpending"]};
        BOOST_REQUIRE_EQUAL(inputs.size(), mtx.vin.size());
        // Pinned, so that a generator emitting fewer spends than it should
        // cannot pass by iterating over a shorter list.
        BOOST_REQUIRE_EQUAL(inputs.size(), 7U);
        for (size_t i{0}; i < inputs.size(); ++i) {
            const UniValue& in{inputs[i]};
            const size_t idx(in["given"]["txinIndex"].getInt<int>());
            BOOST_REQUIRE(idx < mtx.vin.size());

            // Re-derive from the published tree what an implementer would:
            // Merkle root, spent scriptPubKey, leaf hash and control block.
            std::vector<VectorLeaf> leaves;
            const uint256 derived_root{WalkTree(in["given"]["scriptTree"], leaves)};
            const UniValue& in_inter{in["intermediary"]};
            BOOST_CHECK_EQUAL(HexStr(derived_root), in_inter["merkleRoot"].get_str());
            const CScript derived_spk{CScript() << OP_2 << ToByteVector(derived_root)};
            BOOST_CHECK_EQUAL(HexStr(derived_spk), HexStr(spent[idx].scriptPubKey));

            const int leaf_id{in["given"]["leafId"].getInt<int>()};
            const auto leaf_it{std::find_if(leaves.begin(), leaves.end(),
                                            [&](const auto& l) { return l.id == leaf_id; })};
            BOOST_REQUIRE(leaf_it != leaves.end());
            BOOST_CHECK_EQUAL(HexStr(leaf_it->hash), in_inter["leafHash"].get_str());
            std::vector<unsigned char> derived_control{
                static_cast<unsigned char>(leaf_it->version | 1)};
            derived_control.insert(derived_control.end(), leaf_it->path.begin(),
                                   leaf_it->path.end());
            BOOST_CHECK_EQUAL(HexStr(derived_control), in_inter["controlBlock"].get_str());

            // The commitment a leaf carries is the scheme byte followed by
            // the tagged hash of the public key. Deriving it from the
            // published key is the step that makes these vectors checkable
            // without the opcode: it is plain hashing.
            const UniValue& pubkeys{in["given"]["pubkeys"]};
            const UniValue& schemes{in["given"]["schemes"]};
            const UniValue& commitments{in_inter["pubkeyCommitments"]};
            BOOST_REQUIRE_EQUAL(pubkeys.size(), commitments.size());
            BOOST_REQUIRE_EQUAL(schemes.size(), commitments.size());
            const std::map<std::string, uint8_t> scheme_bytes{
                {"ml-dsa-44", 1}, {"slh-dsa-sha2-128s", 2}};
            for (size_t k{0}; k < pubkeys.size(); ++k) {
                const std::vector<unsigned char> pubkey{ParseHex(pubkeys[k].get_str())};
                HashWriter ss{TaggedHash("PQPubKeyHash")};
                ss.write(MakeByteSpan(pubkey));
                const uint256 pubkey_hash{ss.GetSHA256()};
                const auto sb{scheme_bytes.find(schemes[k].get_str())};
                BOOST_REQUIRE_MESSAGE(sb != scheme_bytes.end(),
                                      "unknown scheme name " + schemes[k].get_str());
                std::vector<unsigned char> derived_commitment{sb->second};
                derived_commitment.insert(derived_commitment.end(),
                                          pubkey_hash.begin(), pubkey_hash.end());
                BOOST_CHECK_EQUAL(HexStr(derived_commitment), commitments[k].get_str());

                // And the leaf really pushes it. Without this the published
                // commitment is only checked against itself, since a wrong
                // public key with a matching wrong commitment would agree.
                const auto found{std::search(leaf_it->script.begin(), leaf_it->script.end(),
                                             derived_commitment.begin(),
                                             derived_commitment.end())};
                BOOST_CHECK_MESSAGE(found != leaf_it->script.end(),
                                    "commitment absent from the leaf script");
            }

            const CScriptWitness& wit{tx.vin[idx].scriptWitness};

            // The padded row names the size of the element it carries, and
            // that element is what makes the row worth having: it is over
            // the 520-byte limit every other leaf lives under.
            const UniValue& padding{in["given"]["paddingSize"]};
            if (!padding.isNull()) {
                const auto want{static_cast<size_t>(padding.getInt<int>())};
                BOOST_REQUIRE(!wit.stack.empty());
                BOOST_CHECK_EQUAL(wit.stack.front().size(), want);
                BOOST_CHECK(want > MAX_SCRIPT_ELEMENT_SIZE);
                BOOST_CHECK(want <= PQ_MAX_ELEMENT_SIZE);
            }

            // The hybrid row names an x-only key alongside the PQ ones, and
            // it has to be the key the leaf checks, for the same reason the
            // PQ commitments do.
            const UniValue& ec_pubkey{in["given"]["ecPubkey"]};
            if (!ec_pubkey.isNull()) {
                const std::vector<unsigned char> ec{ParseHex(ec_pubkey.get_str())};
                BOOST_CHECK_EQUAL(ec.size(), 32U);
                const auto found_ec{std::search(leaf_it->script.begin(), leaf_it->script.end(),
                                                ec.begin(), ec.end())};
                BOOST_CHECK_MESSAGE(found_ec != leaf_it->script.end(),
                                    "x-only key absent from the leaf script");
            }

            // The published sighash, recomputed. This is the field an
            // implementer most needs to agree on, and the annex case is
            // where agreement is easiest to lose: the annex is dropped from
            // the stack before execution and reappears only as a hash
            // inside the message.
            ScriptExecutionData execdata;
            execdata.m_tapleaf_hash_init = true;
            execdata.m_tapleaf_hash = leaf_it->hash;
            execdata.m_codeseparator_pos_init = true;
            execdata.m_codeseparator_pos = 0xFFFFFFFF;
            execdata.m_annex_init = true;
            const UniValue& annex{in["given"]["annex"]};
            execdata.m_annex_present = !annex.isNull();
            if (execdata.m_annex_present) {
                const std::vector<unsigned char> annex_bytes{ParseHex(annex.get_str())};
                BOOST_CHECK_EQUAL(HexStr(wit.stack.back()), annex.get_str());
                execdata.m_annex_hash = (HashWriter{} << annex_bytes).GetSHA256();
            }
            // A leaf that checks nothing signs nothing, and publishes no
            // message or sighash; there is no signature for them to belong
            // to. Everything above still applies to it.
            if (!in_inter["sigHash"].isNull()) {
                const auto hash_type{static_cast<uint8_t>(in["given"]["hashType"].getInt<int>())};
                uint256 sighash;
                BOOST_REQUIRE(SignatureHashSchnorr(sighash, execdata, tx, idx, hash_type,
                                                   SigVersion::TAPSCRIPT, txdata,
                                                   MissingDataBehavior::FAIL));
                BOOST_CHECK_EQUAL(HexStr(sighash), in_inter["sigHash"].get_str());

                // The published message is what that sighash is the tagged
                // hash of. Checking the two against each other is what keeps
                // sigMsg from being a field nothing reads.
                const std::vector<unsigned char> sig_msg{ParseHex(in_inter["sigMsg"].get_str())};
                HashWriter msg_hasher{TaggedHash("TapSighash")};
                msg_hasher.write(MakeByteSpan(sig_msg));
                BOOST_CHECK_EQUAL(HexStr(msg_hasher.GetSHA256()), in_inter["sigHash"].get_str());
            } else {
                BOOST_CHECK(in_inter["sigMsg"].isNull());
                BOOST_CHECK(schemes.empty());
            }

            // The witness in the signed transaction is the published one.
            const UniValue& wit_expected{in["expected"]["witness"]};
            BOOST_REQUIRE_EQUAL(wit.stack.size(), wit_expected.size());
            for (size_t k{0}; k < wit.stack.size(); ++k) {
                BOOST_CHECK_EQUAL(HexStr(wit.stack[k]), wit_expected[k].get_str());
            }

            ScriptError serror;
            const bool ok{VerifyScript(
                tx.vin[idx].scriptSig, spent[idx].scriptPubKey, &wit, flags,
                TransactionSignatureChecker(&tx, idx, spent[idx].nValue, txdata,
                                            MissingDataBehavior::ASSERT_FAIL),
                &serror)};
            BOOST_CHECK_MESSAGE(ok, "input " + util::ToString(idx) + ": " +
                                        ScriptErrorString(serror));
        }
    }

    // ---- invalid spends --------------------------------------------------
    // The vectors name the failure in spec terms; this maps each onto the
    // script error the implementation reports. Several spec-level errors
    // collapse onto one ScriptError, which is why the mapping is explicit.
    const std::map<std::string, ScriptError> expected_errors{
        {"invalid signature", SCRIPT_ERR_PQSIG},
        {"public key does not match the commitment", SCRIPT_ERR_PQSIG_PUBKEYHASH},
        {"wrong object size for the scheme", SCRIPT_ERR_PQSIG_SIZE},
        {"invalid hash type", SCRIPT_ERR_PQSIG_HASHTYPE},
        {"unknown scheme", SCRIPT_ERR_PQSIG_SCHEME},
        {"witness element too large", SCRIPT_ERR_PUSH_SIZE},
        {"script evaluated false", SCRIPT_ERR_EVAL_FALSE},
    };

    const UniValue& invalid{root["invalidSpending"]};
    BOOST_REQUIRE(invalid.isArray());
    BOOST_REQUIRE_EQUAL(invalid.size(), 11U);
    for (size_t i{0}; i < invalid.size(); ++i) {
        const UniValue& tv{invalid[i]};
        const std::string id{tv["id"].get_str()};
        const CMutableTransaction mtx{DecodeTx(tv["given"]["rawTx"].get_str())};
        const UniValue& utxo{tv["given"]["utxoSpent"]};
        const std::vector<unsigned char> spk{ParseHex(utxo["scriptPubKey"].get_str())};
        std::vector<CTxOut> spent{
            {utxo["amountSats"].getInt<int64_t>(), CScript(spk.begin(), spk.end())}};

        const CTransaction tx{mtx};
        PrecomputedTransactionData txdata;
        txdata.Init(tx, std::vector<CTxOut>{spent});

        ScriptError serror;
        const bool ok{VerifyScript(
            tx.vin[0].scriptSig, spent[0].scriptPubKey, &tx.vin[0].scriptWitness,
            flags,
            TransactionSignatureChecker(&tx, 0, spent[0].nValue, txdata,
                                        MissingDataBehavior::ASSERT_FAIL),
            &serror)};
        BOOST_CHECK_MESSAGE(!ok, id + ": accepted but must fail");
        const std::string error{tv["expected"]["error"].get_str()};
        const auto it{expected_errors.find(error)};
        BOOST_REQUIRE_MESSAGE(it != expected_errors.end(),
                              id + ": unmapped error \"" + error + "\"");
        BOOST_CHECK_MESSAGE(serror == it->second,
                            id + ": expected " + ScriptErrorString(it->second) +
                                ", got " + ScriptErrorString(serror));
    }
}

BOOST_AUTO_TEST_SUITE_END()
